# This rule is not used by the project resource-action-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over ops.yusaozdemir.de.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: resource-action-operator
    app.kubernetes.io/managed-by: kustomize
  name: resourceaction-admin-role
rules:
- apiGroups:
  - ops.yusaozdemir.de
  resources:
  - resourceactions
  verbs:
  - '*'
- apiGroups:
  - ops.yusaozdemir.de
  resources:
  - resourceactions/status
  verbs:
  - get
