# This rule is not used by the project resource-action-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to ops.yusaozdemir.de resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: resource-action-operator
    app.kubernetes.io/managed-by: kustomize
  name: resourceaction-viewer-role
rules:
- apiGroups:
  - ops.yusaozdemir.de
  resources:
  - resourceactions
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ops.yusaozdemir.de
  resources:
  - resourceactions/status
  verbs:
  - get
